name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - [gcc, g++]
          - [clang, clang++]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: | 
        sudo apt-get install libeigen3-dev -y
        sudo apt-get install clang -y

    - name: Configure CMake
      run: |
        mkdir ${{github.workspace}}/c/build && cd build
        cmake -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              -D CMAKE_C_COMPILER=${{ matrix.compiler[0] }} \
              -D CMAKE_CXX_COMPILER=${{ matrix.compiler[1] }} \
              --log-context ..

    - name: Build
      run: cmake --build ${{github.workspace}}/c/build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: ${{ github.workspace }}/c/build
      run: ctest -C ${{ env.BUILD_TYPE }} .
      
  # codecov:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       submodules: true
  #       fetch-depth: 0
  #   - name: Install Dependencies
  #     run: sudo apt-get install libeigen3-dev -y
  #   - name: Configure CMake
  #     run: |
  #       mkdir ${{github.workspace}}/build && cd build
  #       cmake -D CMAKE_BUILD_TYPE=Debug \
  #             -D ULQR_CODE_COVERAGE=ON \
  #             --log-context ..
  #   - name: Build
  #     run: cmake --build ${{ github.workspace }}/build
  #   - name: Run Tests
  #     working-directory: ${{ github.workspace }}/build
  #     run: ctest .
  #   - name: Process code coverage results
  #     run: gcov **/*.o
  #   - name: Upload Coverage to Codecov
  #     run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports."

  # arduino:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Setup Arduino CLI
  #     uses: arduino/setup-arduino-cli@v1

  #   - name: Install Arduino CLI
  #     run: |
  #       arduino-cli core update-index
  #       arduino-cli core install arduino:avr

  #   - name: Compile Arduino Example
  #     run: |
  #       cd ${{ github.workspace }}/examples
  #       arduino-cli compile -b arduino:avr:nano --libraries ../.. arduino_slap
        