[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
RobotZoo = "74be38bb-dcc2-4b9e-baf3-d6373cd95f10"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
